version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=sebas
      - POSTGRES_PASSWORD=sebas123
    ports:
      - '5432:5432'
    volumes:
    # SÃ³lo para Windows
     # - ./postgres_data:/var/lib/postgresql
      - ./postgres_data:/var/lib/postgresql
   